### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by karan** [mfunaro/handiman-phoenix#1]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by mfunaro** [comment]
The source code is open and on GitHub, therefore I would call it open source. Regardless, thanks for the heads up, I did forget to add a license. 
Added here: ec284bf56806523d0206eaa8a721a09b235ecae3
